workflows:
  android-release:
    name: Android Release
    environment:
      groups:
        - your_environment_variables
      vars:
        CM_FLUTTER_VERSION: "3.22.0"
    
    scripts:
      - name: Build with Verbose Logging
        script: |
          flutter clean
          flutter pub get --verbose
          flutter build apk --release --verbose --no-tree-shake-icons

    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      
