scripts:
  - name: Build with Latest Flutter
    script: |
      flutter channel master
      flutter upgrade
      flutter --version
      flutter clean
      flutter pub get
      flutter build apk --release --verbose
