workflows:
  default-workflow:
    name: Workflow
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Run tests
        script: flutter test
    artifacts:
      - build/**/outputs/**/*.apk
