workflows:
  build-android:
    name: Build Android APK
    working_directory: portfolio_app
    environment:
      flutter:"3.22.0"
    scripts:
      - flutter pub get
      - flutter build apk
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
