workflows:
  build-android:
    name: Build Android APK
    working_directory: portfolio_app
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build apk --android-skip-build-dependency-validation

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
