name: portfolio_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^3.0.2   # (updated for Dart 3.x compatibility)

flutter_launcher_icons:
  android: true            # ✅ Use `true` instead of a string
  ios: true
  image_path: "assets/coverfoto.png"

flutter:
  uses-material-design: true

  assets:
    - assets/coverfoto.png
